name: Child
run-name: "Deploying to ${{ inputs.environment }} by @${{ github.actor }}"

on:
  workflow_call:
    inputs:
      environment:
        description: 'Target environment'
        type: string
        required: true
        default: 'staging'

jobs:
  foo:
    runs-on: ubuntu-slim
    steps:
      - name: Example job
        run: echo "Example job"
