run-name: "Deploying to ${{ inputs.environment }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: [linux]
    steps:
      - name: Deploying code
        run: echo "Deploying to ${{ inputs.environment }}"
