name: Entrypoint
run-name: "Deploying to ${{ inputs.environment }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - staging
          - production

jobs:
  analyze:
    runs-on: ubuntu-slim
    steps:
      - name: Analyzing code
        run: echo "Analyzing ${{ inputs.environment }}"
  deploy-a:
    needs: analyze
    runs-on: ubuntu-slim
    steps:
      - name: Deploying code
        run: echo "Triggering child workflow a"
      - uses: ./.github/workflows/child.yaml
        with:
          environment: 'staging'
  deploy-b:
    needs: analyze
    runs-on: ubuntu-slim
    steps:
      - name: Deploying code
        run: echo "Triggering child workflow b"
      - uses: ./.github/workflows/child.yaml
        with:
          environment: 'production'
  skip:
    needs:
      - deploy-a
      - deploy-b
    runs-on: ubuntu-slim
    if: false
    steps:
      - name: Skipping
        run: echo "Skipping"
