name: Entrypoint
run-name: "Deploying to ${{ inputs.environment }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        required: true
        default: 'staging'
        options:
          - staging
          - production

jobs:
  analyze:
    runs-on: ubuntu-slim
    steps:
      - name: Analyzing code
        run: echo "Analyzing ${{ inputs.environment }}"
  deploy:
    needs: analyze
    runs-on: ubuntu-slim
    steps:
      - name: Deploying code
        run: echo "Deploying to ${{ inputs.environment }}"
  skip:
    runs-on: ubuntu-slim
    if: false
    steps:
      - name: Skipping
        run: echo "Skipping"
